# Задание 1

* Импорт бибилиотеки NumPy с общепринятым сокращением (import numpy as np)

In [4]:
# Импорт бибилиотеки NumPy с общепринятым сокращением np
import numpy as np

# Проверка версии импортированной библиотеки
print(f"NumPy версия: {np.__version__}")

NumPy версия: 2.0.2


# Задание 2

* Создание (примеры) массивов

In [12]:
# Создание массива из списка

# Пример 1
list_1 = [0, 2, 3, 4, 5]

arr_1 = np.array(list_1)
print(arr_1)

# Пример 2
list_2 = list(range(20))

arr_2 = np.array(list_2)
print(arr_2)

# Пример 3
list_3 = [x**2 for x in range(8)]

arr_3 = np.array(list_3)
print(arr_3)

[0 2 3 4 5]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  4  9 16 25 36 49]


In [52]:
# Создание одномерного массива
arr_1 = np.array([1, 2, 3, 6, 0, 4])
print('Одномерный массив:\n')
print(arr_1)
print()

# Создание двумерного массива
arr_2 = np.array([[0, 2, 3], [4, 34, 6], [7, 6, 9]])
print('Двумерный массив:\n')
print(arr_2)
print()

# Создание многомерно массива
arr_3 = np.array([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
    [[19, 20, 21], [22, 23, 24], [25, 26, 27]]
])
print('Многомерный массив:\n')
print(arr_3)
print()

Одномерный массив:

[1 2 3 6 0 4]

Двумерный массив:

[[ 0  2  3]
 [ 4 34  6]
 [ 7  6  9]]

Многомерный массив:

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]



* Функция **np.zeros()** в библиотеке NumPy создаёт новый массив, заполненный нулями.

* Функция **np.ones()** создаёт массив заданной формы и типа, заполненный единицами.

* Функция **np.arange()** создаёт массив с равномерно расположенными значениями внутри заданного интервала.

In [29]:
# Создание массива с помощью функции np.zeros()
zeros_arr_1 = np.zeros(6)
print(zeros_arr_1)
print()

zeros_arr_2 = np.zeros((5, 3)) # Массив 5x3
print(zeros_arr_2)
print()

# Создание массива с помощью функции np.ones()
ones_arr_1 = np.ones(6)
print(ones_arr_1)
print()

ones_arr_2 = np.ones((2, 3)) # Массив 2x3
print(ones_arr_2)
print()

# Создание массива с помощью функции np.arange()
arange_arr = np.arange(1, 10, 2)
print(arange_arr)
print()

[0. 0. 0. 0. 0. 0.]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[1. 1. 1. 1. 1. 1.]

[[1. 1. 1.]
 [1. 1. 1.]]

[1 3 5 7 9]



# Задание 3

## Демонстрация атрибутов


*   Вывод формы **shape**
*   Вывод типа данных **dtype**








In [53]:
arr = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]) # Массив
print('Массив:\n', arr)
print("\nФорма:", np.shape(arr))
print("\nТип данных:", arr.dtype)

Массив:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Форма: (3, 4)

Тип данных: int64


# Задание 4

* Индексирование и срезы

In [46]:
# Индексирование
arr = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]])
print('Массив:\n', arr)

print("\n1. Получение отдельного элемента:")
element = arr[1, 2]  # Строка 2, столбец 3 (но индексирование строк и столбцов с 0)
print(f"arr[1, 2] = {element}")

print("\n2. Получение целой строки:")
row_1 = arr[1]       # Строка 2 (индекс 1)
print(f"arr[1] = {row_1}")

print("\n3. Получение целого столбца:")
col_2 = arr[:, 2]    # Столбец 3 (индекс 2)
print(f"arr[:, 2] = {col_2}")

Массив:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

1. Получение отдельного элемента:
arr[1, 2] = 6

2. Получение целой строки:
arr[1] = [4 5 6 7]

3. Получение целого столбца:
arr[:, 2] = [ 2  6 10]


In [48]:
# Срезы
arr = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]])
print('Массив:\n', arr)

print("\n1. Срез строк:")
rows_slice = arr[0:2]  # Строки с 0 по 1 (2 не включается)
print(f"arr[0:2] = \n{rows_slice}")  # [[0 1 2 3], [4 5 6 7]]

print("\n2. Срез столбцов:")
cols_slice = arr[:, 1:3]  # Все строки, столбцы с 1 по 2
print(f"arr[:, 1:3] = \n{cols_slice}")  # [[1 2], [5 6], [9 10]]

print("\n3. Срез и строк и столбцов:")
sub_array = arr[1:3, 0:2]  # Строки 1-2, столбцы 0-1
print(f"arr[1:3, 0:2] = \n{sub_array}")  # [[4 5], [8 9]]

print("\n4. Срез с шагом:")
step_slice = arr[::2, ::2]  # Каждая вторая строка, каждый второй столбец
print(f"arr[::2, ::2] = \n{step_slice}")  # [[0 2], [8 10]]

Массив:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

1. Срез строк:
arr[0:2] = 
[[0 1 2 3]
 [4 5 6 7]]

2. Срез столбцов:
arr[:, 1:3] = 
[[ 1  2]
 [ 5  6]
 [ 9 10]]

3. Срез и строк и столбцов:
arr[1:3, 0:2] = 
[[4 5]
 [8 9]]

4. Срез с шагом:
arr[::2, ::2] = 
[[ 0  2]
 [ 8 10]]


In [49]:
# Извлечение подмассивов
arr = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]])
print('Массив:\n', arr)

print("\n1. Подмассив 2x2 из центра:")
center_sub = arr[0:2, 1:3]  # Строки 0-1, столбцы 1-2
print(f"arr[0:2, 1:3] = \n{center_sub}")  # [[1 2], [5 6]]

print("\n2. Последние два столбца:")
last_cols = arr[:, -2:]  # Все строки, последние 2 столбца
print(f"arr[:, -2:] = \n{last_cols}")  # [[2 3], [6 7], [10 11]]

print("\n3. Первая и последняя строки:")
first_last = arr[::2]  # С шагом 2: строка 0 и 2
print(f"arr[::2] = \n{first_last}")  # [[0 1 2 3], [8 9 10 11]]

Массив:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

1. Подмассив 2x2 из центра:
arr[0:2, 1:3] = 
[[1 2]
 [5 6]]

2. Последние два столбца:
arr[:, -2:] = 
[[ 2  3]
 [ 6  7]
 [10 11]]

3. Первая и последняя строки:
arr[::2] = 
[[ 0  1  2  3]
 [ 8  9 10 11]]


# Задание 5


## Векторные операции и базовая статистика


*   поэлементное сложение или умножение массивов
*   вычисление средней величины **mean** или другой простой статистики



In [55]:
# Поэлементные операции

arr_1 = np.array([1, 2, 3, 4, 5])
arr_2 = np.array([10, 20, 30, 40, 50])

addition = arr_1 + arr_2
print("1. Поэлементное сложение массиов:")
print(f"Результат: {addition}")

# 2. Поэлементное умножение
multiplication = arr_1 * arr_2
print("\n2. Поэлементное умножение массивов:")
print(f"Результат: {multiplication}")

# 3. Поэлементное вычитание
subtraction = arr_2 - arr_1
print("\n3. Поэлементное вычитание массиов:")
print(f"Результат: {subtraction}")

# 4. Поэлементное деление
division = arr_2 / arr_1
print("\n4. Поэлементное деление массиов:")
print(f"Результат: {division}")

# 5. Поэлементное возведение в степень
power = arr_1 ** 2
print("\n5. Поэлементное возведение в степень массиов:")
print(f"Результат: {power}")



1. Поэлементное сложение массиов:
Результат: [11 22 33 44 55]

2. Поэлементное умножение массивов:
Результат: [ 10  40  90 160 250]

3. Поэлементное вычитание массиов:
Результат: [ 9 18 27 36 45]

4. Поэлементное деление массиов:
Результат: [10. 10. 10. 10. 10.]

5. Поэлементное возведение в степень массиов:
Результат: [ 1  4  9 16 25]


In [57]:
# Статистика

arr = np.array([12, 15, 8, 20, 5, 18, 10, 25, 3, 22])

print(f"Массив:\n {arr}\n")

# 1. Среднее значение (mean)
mean_value = np.mean(arr)
print("1. Среднее значение (np.mean):")
print(f"Результат: {mean_value:.2f}")

# 2. Медиана (median)
median_value = np.median(arr)
print("\n2. Медиана (np.median):")
print(f"Результат: {median_value}")

# 3. Стандартное отклонение (std)
std_value = np.std(arr)
print("\n3. Стандартное отклонение (np.std):")
print(f"Результат: {std_value:.2f}")

# 4. Дисперсия (variance)
var_value = np.var(arr)
print("\n4. Дисперсия (np.var):")
print(f"Результат: {var_value:.2f}")

# 5. Минимальное и максимальное значения
min_value = np.min(arr)
max_value = np.max(arr)
print("\n5. Минимальное и максимальное значения:")
print(f"Минимум: {min_value}")
print(f"Максимум: {max_value}")
print(f"Диапазон: {max_value - min_value}\n")

# 6. Сумма всех элементов
sum_value = np.sum(arr)
print("\n6. Сумма всех элементов (np.sum):")
print(f"Результат: {sum_value}")


# 7. Процентили
percentile_25 = np.percentile(arr, 25)
percentile_75 = np.percentile(arr, 75)
print("\n7. Процентили:")
print(f"25-й процентиль (Q1): {percentile_25}")
print(f"75-й процентиль (Q3): {percentile_75}\n")

Массив:
 [12 15  8 20  5 18 10 25  3 22]

1. Среднее значение (np.mean):
Результат: 13.80

2. Медиана (np.median):
Результат: 13.5

3. Стандартное отклонение (np.std):
Результат: 7.04

4. Дисперсия (np.var):
Результат: 49.56

5. Минимальное и максимальное значения:
Минимум: 3
Максимум: 25
Диапазон: 22


6. Сумма всех элементов (np.sum):
Результат: 138

7. Процентили:
25-й процентиль (Q1): 8.5
75-й процентиль (Q3): 19.5

